/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1312084.pkg1312110;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import pkg1312084.pkg1312110.DCrypto;

/**
 *
 * @author WinDuy 7
 */
public class main_GUI extends javax.swing.JFrame {

    /**
     * Creates new form jFrame
     */
    PrivateKey mainPrivateKey = null;
    PublicKey mainPublicKey = null;
    //KeyPair mainKeyPair;
    public main_GUI() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        FileChooser = new javax.swing.JFileChooser();
        FileChooser2 = new javax.swing.JFileChooser();
        FileChooser3 = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MainTab = new javax.swing.JTabbedPane();
        SymmetricTab = new javax.swing.JPanel();
        CreateSecretKey = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CommandLine_Sym = new javax.swing.JTextArea();
        KeySizeBox_Sym = new javax.swing.JTextField();
        KeysizeLabel_Sym = new javax.swing.JLabel();
        ExportSymmetricKey = new javax.swing.JButton();
        EncryptButton_Sym = new javax.swing.JButton();
        DecryptButton_Sym = new javax.swing.JButton();
        InputFileField_Sym = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        OutputFileField_Sym = new javax.swing.JTextField();
        FileButton_3 = new javax.swing.JButton();
        FileButton_4 = new javax.swing.JButton();
        KeyTab = new javax.swing.JPanel();
        AsymmetricTab = new javax.swing.JPanel();
        OutputFileField = new javax.swing.JTextField();
        VerifyButton = new javax.swing.JButton();
        ExportPublic = new javax.swing.JButton();
        EncryptButton = new javax.swing.JButton();
        DecryptButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        KeySizeBox = new javax.swing.JTextField();
        ExportPrivate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ImportPublicKey = new javax.swing.JButton();
        InputFileField = new javax.swing.JTextField();
        ImportPrivateKey = new javax.swing.JButton();
        FileButton_1 = new javax.swing.JButton();
        CreateKeyPairButton = new javax.swing.JButton();
        FileButton_2 = new javax.swing.JButton();
        SignButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommandLine = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CreateSecretKey.setText("Create Symmetric Key");
        CreateSecretKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateSecretKeyActionPerformed(evt);
            }
        });

        CommandLine_Sym.setEditable(false);
        CommandLine_Sym.setBackground(new java.awt.Color(0, 0, 0));
        CommandLine_Sym.setColumns(20);
        CommandLine_Sym.setForeground(new java.awt.Color(0, 255, 0));
        CommandLine_Sym.setLineWrap(true);
        CommandLine_Sym.setRows(5);
        CommandLine_Sym.setWrapStyleWord(true);
        CommandLine_Sym.setAutoscrolls(false);
        jScrollPane2.setViewportView(CommandLine_Sym);

        KeySizeBox_Sym.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        KeySizeBox_Sym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeySizeBox_SymActionPerformed(evt);
            }
        });

        KeysizeLabel_Sym.setText("Điền keysize");

        ExportSymmetricKey.setText("Export Symmetric Key");
        ExportSymmetricKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportSymmetricKeyActionPerformed(evt);
            }
        });

        EncryptButton_Sym.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EncryptButton_Sym.setText("Encrypt");
        EncryptButton_Sym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptButton_SymActionPerformed(evt);
            }
        });

        DecryptButton_Sym.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DecryptButton_Sym.setText("Decrypt");
        DecryptButton_Sym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptButton_SymActionPerformed(evt);
            }
        });

        InputFileField_Sym.setEditable(false);
        InputFileField_Sym.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        InputFileField_Sym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFileField_SymActionPerformed(evt);
            }
        });

        jLabel5.setText("Input File");

        jLabel6.setText("Output File");

        OutputFileField_Sym.setEditable(false);
        OutputFileField_Sym.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        OutputFileField_Sym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputFileField_SymActionPerformed(evt);
            }
        });

        FileButton_3.setText("...");
        FileButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButton_3ActionPerformed(evt);
            }
        });

        FileButton_4.setText("...");
        FileButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButton_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SymmetricTabLayout = new javax.swing.GroupLayout(SymmetricTab);
        SymmetricTab.setLayout(SymmetricTabLayout);
        SymmetricTabLayout.setHorizontalGroup(
            SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SymmetricTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ExportSymmetricKey, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SymmetricTabLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SymmetricTabLayout.createSequentialGroup()
                            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(KeysizeLabel_Sym)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(KeySizeBox_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CreateSecretKey))
                            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(EncryptButton_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(DecryptButton_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(InputFileField_Sym)
                                        .addComponent(OutputFileField_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FileButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FileButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(12, 12, 12))
                        .addComponent(jScrollPane2))
                    .addGap(15, 15, 15)))
        );
        SymmetricTabLayout.setVerticalGroup(
            SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SymmetricTabLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(ExportSymmetricKey)
                .addGap(59, 59, 59))
            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SymmetricTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SymmetricTabLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(KeySizeBox_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KeysizeLabel_Sym, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(58, 58, 58))
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addComponent(CreateSecretKey)
                                    .addGap(50, 50, 50)))
                            .addGap(18, 18, 18))
                        .addGroup(SymmetricTabLayout.createSequentialGroup()
                            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(InputFileField_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SymmetricTabLayout.createSequentialGroup()
                                    .addComponent(FileButton_3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FileButton_4)
                                        .addComponent(OutputFileField_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(46, 46, 46)
                            .addGroup(SymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DecryptButton_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EncryptButton_Sym, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );

        MainTab.addTab("Symmetric Encryption", SymmetricTab);

        javax.swing.GroupLayout KeyTabLayout = new javax.swing.GroupLayout(KeyTab);
        KeyTab.setLayout(KeyTabLayout);
        KeyTabLayout.setHorizontalGroup(
            KeyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        KeyTabLayout.setVerticalGroup(
            KeyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        MainTab.addTab("Key Directory", KeyTab);

        OutputFileField.setEditable(false);
        OutputFileField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        OutputFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputFileFieldActionPerformed(evt);
            }
        });

        VerifyButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VerifyButton.setText("Verify");
        VerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyButtonActionPerformed(evt);
            }
        });

        ExportPublic.setText("Export Public Key");
        ExportPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportPublicActionPerformed(evt);
            }
        });

        EncryptButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EncryptButton.setText("Encrypt");
        EncryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptButtonActionPerformed(evt);
            }
        });

        DecryptButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DecryptButton.setText("Decrypt");
        DecryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Input File");

        jLabel4.setText("Output File");

        KeySizeBox.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        KeySizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeySizeBoxActionPerformed(evt);
            }
        });

        ExportPrivate.setText("Export Private Key");
        ExportPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportPrivateActionPerformed(evt);
            }
        });

        jLabel1.setText("Điền keysize");

        ImportPublicKey.setText("ImportPublicKey");
        ImportPublicKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportPublicKeyActionPerformed(evt);
            }
        });

        InputFileField.setEditable(false);
        InputFileField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        InputFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFileFieldActionPerformed(evt);
            }
        });

        ImportPrivateKey.setText("ImportPrivateKey");
        ImportPrivateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportPrivateKeyActionPerformed(evt);
            }
        });

        FileButton_1.setText("...");
        FileButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButton_1ActionPerformed(evt);
            }
        });

        CreateKeyPairButton.setText("Create RSA Key Pair");
        CreateKeyPairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateKeyPairButtonActionPerformed(evt);
            }
        });

        FileButton_2.setText("...");
        FileButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButton_2ActionPerformed(evt);
            }
        });

        SignButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SignButton.setText("Sign");
        SignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignButtonActionPerformed(evt);
            }
        });

        CommandLine.setEditable(false);
        CommandLine.setBackground(new java.awt.Color(0, 0, 0));
        CommandLine.setColumns(20);
        CommandLine.setForeground(new java.awt.Color(0, 255, 0));
        CommandLine.setLineWrap(true);
        CommandLine.setRows(5);
        CommandLine.setWrapStyleWord(true);
        CommandLine.setAutoscrolls(false);
        jScrollPane1.setViewportView(CommandLine);

        javax.swing.GroupLayout AsymmetricTabLayout = new javax.swing.GroupLayout(AsymmetricTab);
        AsymmetricTab.setLayout(AsymmetricTabLayout);
        AsymmetricTabLayout.setHorizontalGroup(
            AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsymmetricTabLayout.createSequentialGroup()
                        .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(KeySizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ExportPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CreateKeyPairButton))
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addComponent(ExportPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(EncryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DecryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VerifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                        .addComponent(ImportPublicKey)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ImportPrivateKey))
                                    .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(InputFileField)
                                        .addComponent(OutputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FileButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FileButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1))
                .addGap(20, 20, 20))
        );
        AsymmetricTabLayout.setVerticalGroup(
            AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsymmetricTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AsymmetricTabLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(KeySizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExportPublic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExportPrivate))
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addComponent(CreateKeyPairButton)
                                .addGap(50, 50, 50)))
                        .addGap(18, 18, 18))
                    .addGroup(AsymmetricTabLayout.createSequentialGroup()
                        .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AsymmetricTabLayout.createSequentialGroup()
                                .addComponent(FileButton_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FileButton_2)
                                    .addComponent(OutputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImportPrivateKey)
                            .addComponent(ImportPublicKey))
                        .addGap(17, 17, 17)
                        .addGroup(AsymmetricTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DecryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EncryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VerifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        EncryptButton.getAccessibleContext().setAccessibleName("EncryptButton");
        DecryptButton.getAccessibleContext().setAccessibleName("DecryptButton");

        MainTab.addTab("Asymmetric Encryption", AsymmetricTab);
        AsymmetricTab.getAccessibleContext().setAccessibleName("Asymmetric Encryption");

        jMenu1.setText("Help");
        MenuBar.add(jMenu1);

        jMenu2.setText("About");
        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MainTab.getAccessibleContext().setAccessibleName("mainTab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeySizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeySizeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeySizeBoxActionPerformed

    private void InputFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFileFieldActionPerformed

    private void OutputFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputFileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputFileFieldActionPerformed

    private void FileButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButton_1ActionPerformed
        // TODO add your handling code here:
        //Handle open button action.
        if (evt.getSource() == FileButton_1) 
        {
            JFileChooser fc = new JFileChooser();
            int returnVal = fc.showOpenDialog(main_GUI.this);

            if (returnVal == fc.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                InputFileField.setText(file.getPath());
            } 
            else 
            {

            }
       }
    }//GEN-LAST:event_FileButton_1ActionPerformed

    private void FileButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButton_2ActionPerformed
        // TODO add your handling code here:
        //Handle open button action.
        if (evt.getSource() == FileButton_2) 
        {
            JFileChooser fc = new JFileChooser();
            int returnVal = fc.showSaveDialog(main_GUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                OutputFileField.setText(file.getPath());
            } 
            else 
            {

            }
       }
    }//GEN-LAST:event_FileButton_2ActionPerformed

    private void EncryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptButtonActionPerformed
        try {
            if("".equals(InputFileField.getText()) || "".equals(OutputFileField.getText()))
            {
                CommandLine.append("\nInvalid input....");
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            long startTime = System.currentTimeMillis();
            CommandLine.append("\n" + sdf.format(startTime) + " - Begin encrypting file...");
            boolean result = false;
            result = DCrypto.RSAEncryptFile(mainPublicKey, InputFileField.getText(), OutputFileField.getText());
            long endTime = System.currentTimeMillis();
            if(result == true)
                CommandLine.append("\n" + sdf.format(endTime) + " - Encryption completed. ^^");
            else
                CommandLine.append("\n" + sdf.format(endTime) + " - Encryption failed...");
        } catch (IOException ex) {
            Logger.getLogger(main_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EncryptButtonActionPerformed

    private void ExportPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportPublicActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ExportPublic) 
        {
            JFileChooser fc = new JFileChooser();
            if(mainPublicKey == null)
            {
                CommandLine.append("\nPlease create public key first!!!!\n");
                return;
            }
            int returnVal = fc.showSaveDialog(main_GUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) 
            {
                DCrypto.exportPublicKey(mainPublicKey, fc.getSelectedFile().getPath()); 
                CommandLine.append("\nExported public key\n");
            } 
            else 
            {

            }
       }
    }//GEN-LAST:event_ExportPublicActionPerformed

    private void ExportPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportPrivateActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ExportPrivate) 
        {
            JFileChooser fc = new JFileChooser();
            if(mainPrivateKey == null)
            {
                CommandLine.append("\nPlease create private key first!!!!\n");
                return;
            }
            int returnVal = fc.showSaveDialog(main_GUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) 
            {
                DCrypto.exportPrivateKey(mainPrivateKey, fc.getSelectedFile().getPath());
                CommandLine.append("\nExported private key\n");
            } 
            else 
            {

            }
       }
    }//GEN-LAST:event_ExportPrivateActionPerformed

    private void ImportPublicKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportPublicKeyActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ImportPublicKey) 
        {
            JFileChooser fc = new JFileChooser();
            int returnVal = fc.showOpenDialog(main_GUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                mainPublicKey = DCrypto.importPublicKey(file.getPath());
                CommandLine.append("\n=====Imported public key=====");
                CommandLine.append("\n" + DCrypto.keyToString(mainPublicKey));
                CommandLine.append("\n=======End public key========");
            } 
            else 
            {

            }
       }
    }//GEN-LAST:event_ImportPublicKeyActionPerformed

    private void ImportPrivateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportPrivateKeyActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ImportPrivateKey) 
        {
            JFileChooser fc = new JFileChooser();
            int returnVal = fc.showOpenDialog(main_GUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                mainPrivateKey = DCrypto.importPrivateKey(file.getPath());
                CommandLine.append("\n=====Imported private key=====");
                CommandLine.append("\n" + DCrypto.keyToString(mainPrivateKey));
                CommandLine.append("\n=======End private key========");
            } 
            else 
            {

            }
       }
    }//GEN-LAST:event_ImportPrivateKeyActionPerformed

    private void DecryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptButtonActionPerformed
        // TODO add your handling code here:
        if("".equals(InputFileField.getText()) || "".equals(OutputFileField.getText()))
        {
            CommandLine.append("Invalid input....");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        long startTime = System.currentTimeMillis();
        CommandLine.append("\n" + sdf.format(startTime) + " - Begin decrypting file...");
        boolean result = false;
        result = DCrypto.RSADecryptFile(mainPrivateKey, InputFileField.getText(), OutputFileField.getText());
        long endTime = System.currentTimeMillis();
        if(result == true)
            CommandLine.append("\n" + sdf.format(endTime) + " - Decryption completed. ^^");
        else 
            CommandLine.append("\n" + sdf.format(endTime) + " - Decryption failed...");
    }//GEN-LAST:event_DecryptButtonActionPerformed

    private void CreateKeyPairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateKeyPairButtonActionPerformed
        // TODO add your handling code here:
                if(KeySizeBox.getText().equals(""))
        {
            CommandLine.append("\nError: Empty keysize!!!!\n");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        int keySize = Integer.parseInt(KeySizeBox.getText());
        
        if(keySize < 768 || keySize > 16384)
        {
            CommandLine.append("\nInvalid key size! Key size must be between 768 and 16384 bits");
            return;
        }
        if(keySize % 8 != 0)
        {
            CommandLine.append("\nKey size must divisible by 8!!!");
            return;
        }
        
        long startTime = System.currentTimeMillis();
        CommandLine.append("\nGenerating RSA Key Pair at " + sdf.format(startTime));
        
        KeyPair keyPair = DCrypto.createRSAKeyPair(keySize);
        mainPublicKey = keyPair.getPublic();
        mainPrivateKey = keyPair.getPrivate();

        long endTime = System.currentTimeMillis();
        CommandLine.append("\nFinished at " + sdf.format(endTime));
        CommandLine.append("\n=========Public key==========\n" + DCrypto.keyToString(mainPublicKey) );
        CommandLine.append("\n========End public key=======");
        CommandLine.append("\n\n=========Private key=========\n" + DCrypto.keyToString(mainPrivateKey) );
        CommandLine.append("\n========End private key======");
    }//GEN-LAST:event_CreateKeyPairButtonActionPerformed

    private void SignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignButtonActionPerformed
        // TODO add your handling code here:
        try 
        {
            String algorithm = "SHA-256";
            if("".equals(InputFileField.getText()))
            {
                CommandLine.append("Invalid input....");
                return;
            }
            if(mainPrivateKey == null)
            {
                CommandLine.append("\nError: Empty private key!\nPlease import private key!");
                return;
            }
            OutputFileField.setText(InputFileField.getText().concat(".sig"));
            
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            long startTime = System.currentTimeMillis();
            CommandLine.append("\n" + sdf.format(startTime) + " - Begin signing file...");
            boolean result = false;
            
            String hashString = DCrypto.digestFile(InputFileField.getText(), algorithm);
            CommandLine.append("\nHash String: " + hashString);
            String signature = DCrypto.signMess(mainPrivateKey, hashString);
            CommandLine.append("\nSignature created: " + signature);
            
            if("".equals(hashString) || "".equals(signature))
            {
                long endTime = System.currentTimeMillis();
                CommandLine.append("\n" + sdf.format(endTime) + " - Signing failed...");
                return;
            }
            
            
            File signatureFile = new File(OutputFileField.getText());
            signatureFile.createNewFile();
            PrintWriter writer = new PrintWriter(signatureFile);
            writer.println(signature);
            writer.close();
            
            CommandLine.append("\nSignature file " + OutputFileField.getText() + " has been created.");
            long endTime = System.currentTimeMillis();
            CommandLine.append("\n" + sdf.format(endTime) + " - Signing completed.");
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(main_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SignButtonActionPerformed

    private void VerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyButtonActionPerformed
        try 
        {
            // TODO add your handling code here:
            if("".equals(InputFileField.getText()))
            {
                CommandLine.append("Invalid input....");
                return;
            }
            if(mainPublicKey == null)
            {
                CommandLine.append("\nError: Empty public key!\nPlease import public key!");
                return;
            }
            String originFile = InputFileField.getText();
            String signatureFile = originFile + ".sig";
            OutputFileField.setText(signatureFile);
            File testFile = new File(signatureFile);
            if(testFile.exists())
            {
                CommandLine.append("\nChecked. Signature file exist.");
            }
            else
            {
                CommandLine.append("\nSignature file does not exist.");
                return;
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            long startTime = System.currentTimeMillis();
            CommandLine.append("\n" + sdf.format(startTime) + " - Begin verifying file...");
            boolean result = false;
            
            String signature = "";
            FileReader fd = null;
            try
            {
                fd = new FileReader(testFile);
            }
            catch (FileNotFoundException ex)
            {
                Logger.getLogger(main_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader bf = new BufferedReader(fd);
            signature = bf.readLine();
            
            result = DCrypto.verifySign(mainPublicKey, originFile, signature);
            
            long endTime = System.currentTimeMillis();
            
            if(result == true)
                CommandLine.append("\n" + sdf.format(endTime) +" Signatured verified! ^^");
            else
                CommandLine.append("\n" + sdf.format(endTime) +" Signature doesn't match....");
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(main_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VerifyButtonActionPerformed

    private void CreateSecretKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateSecretKeyActionPerformed
        // TODO add your handling code here:
        //DCrypto.generateSecretKey(mode, HEIGHT)
    }//GEN-LAST:event_CreateSecretKeyActionPerformed

    private void KeySizeBox_SymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeySizeBox_SymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeySizeBox_SymActionPerformed

    private void ExportSymmetricKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportSymmetricKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportSymmetricKeyActionPerformed

    private void EncryptButton_SymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptButton_SymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncryptButton_SymActionPerformed

    private void DecryptButton_SymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptButton_SymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecryptButton_SymActionPerformed

    private void InputFileField_SymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFileField_SymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFileField_SymActionPerformed

    private void OutputFileField_SymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputFileField_SymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputFileField_SymActionPerformed

    private void FileButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButton_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileButton_3ActionPerformed

    private void FileButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButton_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileButton_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AsymmetricTab;
    private javax.swing.JTextArea CommandLine;
    private javax.swing.JTextArea CommandLine_Sym;
    private javax.swing.JButton CreateKeyPairButton;
    private javax.swing.JButton CreateSecretKey;
    private javax.swing.JButton DecryptButton;
    private javax.swing.JButton DecryptButton_Sym;
    private javax.swing.JButton EncryptButton;
    private javax.swing.JButton EncryptButton_Sym;
    private javax.swing.JButton ExportPrivate;
    private javax.swing.JButton ExportPublic;
    private javax.swing.JButton ExportSymmetricKey;
    private javax.swing.JButton FileButton_1;
    private javax.swing.JButton FileButton_2;
    private javax.swing.JButton FileButton_3;
    private javax.swing.JButton FileButton_4;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JFileChooser FileChooser2;
    private javax.swing.JFileChooser FileChooser3;
    private javax.swing.JButton ImportPrivateKey;
    private javax.swing.JButton ImportPublicKey;
    private javax.swing.JTextField InputFileField;
    private javax.swing.JTextField InputFileField_Sym;
    private javax.swing.JTextField KeySizeBox;
    private javax.swing.JTextField KeySizeBox_Sym;
    private javax.swing.JPanel KeyTab;
    private javax.swing.JLabel KeysizeLabel_Sym;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField OutputFileField;
    private javax.swing.JTextField OutputFileField_Sym;
    private javax.swing.JButton SignButton;
    private javax.swing.JPanel SymmetricTab;
    private javax.swing.JButton VerifyButton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
